# kubernetes/common/modsecurity-config.yaml                                                                                            
apiVersion: v1                                                                                                                         
kind: ConfigMap                                                                                                                        
metadata:                                                                                                                              
  name: modsecurity-config                                                                                                             
  namespace: common                                                                                                                    
data:                                                                                                                                  
  modsecurity-override.conf: |   
    # change to "On" when ready to enforce                                                                                                      
    SecRuleEngine DetectionOnly                                                                  
    SecRequestBodyAccess On                                                                                                            
    SecResponseBodyAccess Off
    # Whitelist Jaeger UI host
    SecRule REQUEST_HEADERS:Host "@streq jaeger-brazil.karim-portfolio.xyz" \
      "id:9000,phase:1,pass,nolog,ctl:ruleEngine=Off"
    