# kubernetes/common/modsecurity-config.yaml                                                                                            
apiVersion: v1                                                                                                                         
kind: ConfigMap                                                                                                                        
metadata:                                                                                                                              
  name: modsecurity-config                                                                                                             
  namespace: common                                                                                                                    
data:                                                                                                                                  
  modsecurity-override.conf: |   
    # change to "On" when ready to enforce                                                                                                      
    SecRuleEngine DetectionOnly                                                                  
    SecRequestBodyAccess On                                                                                                            
    SecResponseBodyAccess Off