# --- Regional Postgres Database ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-{{ country }}
  namespace: {{ namespace }}
  labels:
    app: postgres
    country: "{{ country }}"
    environment: "{{ env_name }}"
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: postgres
      country: "{{ country }}"
      environment: "{{ env_name }}"
  template:
    metadata:
      labels:
        app: postgres
        country: "{{ country }}"
        environment: "{{ env_name }}"
    spec:
      containers:
        - name: postgres
          image: "{{ image }}"
          env:
            - name: POSTGRES_DB
              value: "futurekawa-postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ country }}-staging-app-secrets"
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ country }}-staging-app-secrets"
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: db-{{ country }}
  namespace: {{ namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres
    country: "{{ country }}"
    environment: "{{ env_name }}"
  ports:
    - port: 5432
      targetPort: 5432
