# --- Regional Kafka UI ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: {{ namespace }}
  labels:
    app: kafka-ui
    country: "{{ country }}"
    environment: "{{ env_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
      country: "{{ country }}"
      environment: "{{ env_name }}"
  template:
    metadata:
      labels:
        app: kafka-ui
        country: "{{ country }}"
        environment: "{{ env_name }}"
    spec:
      containers:
        - name: kafka-ui
          image: "{{ image }}"
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "{{ country }}"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: {{ namespace }}
spec:
  type: NodePort
  selector:
    app: kafka-ui
    country: "{{ country }}"
    environment: "{{ env_name }}"
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ ui_port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui
  namespace: {{ namespace }}
  labels:
    app: kafka-ui
    country: "{{ country }}"
    environment: "{{ env_name }}"
spec:
  rules:
  - host: "{{ ui_host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka-ui
            port:
              number: 8080
