apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ namespace }}
  labels:
    app: mosquitto
    country: "{{ country }}"
    environment: "{{ env_name }}"
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
    log_dest stdout
    log_type subscribe
    log_type all
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: {{ namespace }}
  labels:
    app: mosquitto
    country: "{{ country }}"
    environment: "{{ env_name }}"
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: mosquitto
      country: "{{ country }}"
      environment: "{{ env_name }}"
  template:
    metadata:
      labels:
        app: mosquitto
        country: "{{ country }}"
        environment: "{{ env_name }}"
    spec:
      containers:
        - name: mosquitto
          image: "{{ image }}"
          command: ["mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
          ports:
            - name: mqtt
              containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /etc/mosquitto/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: {{ namespace }}
spec:
  type: ClusterIP
  selector:
    app: mosquitto
    country: "{{ country }}"
    environment: "{{ env_name }}"
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883