apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ country }}-staging-app-secrets"
  namespace: "{{ namespace }}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: "{{ country }}-staging-app-secrets"
    creationPolicy: Owner
  data:
    - secretKey: postgres_user
      remoteRef:
        key: "staging-{{ country }}"
        property: postgres_user
    - secretKey: postgres_password
      remoteRef:
        key: "staging-{{ country }}"
        property: postgres_password
    - secretKey: api_db_user
      remoteRef:
        key: "staging-{{ country }}"
        property: api_db_user
    - secretKey: api_db_password
      remoteRef:
        key: "staging-{{ country }}"
        property: api_db_password
    - secretKey: mqtt_db_user
      remoteRef:
        key: "staging-{{ country }}"
        property: mqtt_db_user
    - secretKey: mqtt_db_password
      remoteRef:
        key: "staging-{{ country }}"
        property: mqtt_db_password
    - secretKey: rabbitmq_user
      remoteRef:
        key: "staging-{{ country }}"
        property: rabbitmq_user
    - secretKey: rabbitmq_password
      remoteRef:
        key: "staging-{{ country }}"
        property: rabbitmq_password
    - secretKey: api_rabbitmq_user
      remoteRef:
        key: "staging-{{ country }}"
        property: api_rabbitmq_user
    - secretKey: api_rabbitmq_password
      remoteRef:
        key: "staging-{{ country }}"
        property: api_rabbitmq_password
    - secretKey: mqtt_rabbitmq_user
      remoteRef:
        key: "staging-{{ country }}"
        property: mqtt_rabbitmq_user
    - secretKey: mqtt_rabbitmq_password
      remoteRef:
        key: "staging-{{ country }}"
        property: mqtt_rabbitmq_password
    - secretKey: alerting_rabbitmq_user
      remoteRef:
        key: "staging-{{ country }}"
        property: alerting_rabbitmq_user
    - secretKey: alerting_rabbitmq_password
      remoteRef:
        key: "staging-{{ country }}"
        property: alerting_rabbitmq_password
    - secretKey: mail_user
      remoteRef:
        key: "staging-{{ country }}"
        property: mail_user
    - secretKey: mail_password
      remoteRef:
        key: "staging-{{ country }}"
        property: mail_password
    - secretKey: alerting_mail_user
      remoteRef:
        key: "staging-{{ country }}"
        property: alerting_mail_user
    - secretKey: alerting_mail_password
      remoteRef:
        key: "staging-{{ country }}"
        property: alerting_mail_password
