---
- name: Deploy Altitude0 Applications to k3s
  hosts: k3s_nodes
  become: yes
  vars:
    env_name: staging
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    
    # Images (can be overridden via -e)
    # central_api_image: "ghcr.io/altitude-0/futurekawa-product:f94cf902787208f362205a433c1369875f690433"
    core_brasil_image: ghcr.io/altitude-0/fk-brasil-core:v1.0.2
    alerting_brasil_image: "ghcr.io/altitude-0/fk-brasil-alerting:v1.0.2"
    mqtt_service_brasil_image: "ghcr.io/altitude-0/fk-brasil-mqtt:v1.0.2"
    core_ecuador_image: "ghcr.io/altitude-0/fk-ecuador-core:v1.0.2"
    alerting_ecuador_image: "ghcr.io/altitude-0/fk-ecuador-alerting:v1.0.2"
    mqtt_service_ecuador_image: "ghcr.io/altitude-0/fk-ecuador-mqtt:v1.0.2"
    core_colombia_image: "ghcr.io/altitude-0/fk-colombia-core:v1.0.2"
    alerting_colombia_image: "ghcr.io/altitude-0/fk-colombia-alerting:v1.0.2"
    mqtt_service_colombia_image: "ghcr.io/altitude-0/fk-colombia-mqtt:v1.0.2"
    # frontend_image: "nginx:1.27-alpine"
    postgres_image: "postgres:16"                                                                                                    
    mosquitto_image: "eclipse-mosquitto:2.0.18"                                                                                        
    mosquitto_ui_image: "cedalo/management-center:2.6.4"
    pgadmin_image: "dpage/pgadmin4:8.12"
    rabbitmq_image: "rabbitmq:3.13-management"
    mailhog_image: "mailhog/mailhog:v1.0.1" 
    
    # Common settings
    app_port: 8080
    replicas: 1
    
    countries:
      - name: brazil
        core_image: "{{ core_brasil_image }}"
        alerting_image: "{{ alerting_brasil_image }}"
        mqtt_image: "{{ mqtt_service_brasil_image }}"

      - name: ecuador
        core_image: "{{ core_ecuador_image }}"
        alerting_image: "{{ alerting_ecuador_image }}"
        mqtt_image: "{{ mqtt_service_ecuador_image }}"

      - name: colombia
        core_image: "{{ core_colombia_image }}"
        alerting_image: "{{ alerting_colombia_image }}"
        mqtt_image: "{{ mqtt_service_colombia_image }}"

  tasks:
    - name: Install dependencies for Kubernetes modules via APT
      apt:
        name: 
          - python3-kubernetes
          - python3-yaml
        state: present

    - name: Ensure Kubernetes collection is installed
      command: ansible-galaxy collection install kubernetes.core
      run_once: true
      delegate_to: localhost
      changed_when: false

    - name: Wait for k3s to be ready
      command: kubectl wait --for=condition=Ready node --all --timeout=180s
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    # --- 1. CENTRAL APPLICATION SERVICES ---
    - name: Create Central Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Namespace
        name: "{{ env_name }}-application"
        state: present

    - name: Apply GHCR Auth to Central Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition: "{{ lookup('template', '../kubernetes/common/ghcr-auth.yaml') }}"
      vars:
        namespace: "{{ env_name }}-application"

    # - name: Deploy Central API
    #   kubernetes.core.k8s:
    #     kubeconfig: "{{ kubeconfig }}"
    #     state: present
    #     definition: "{{ lookup('template', '../kubernetes/central/api.yaml') }}"
    #   vars:
    #     namespace: "{{ env_name }}-application"
    #     image: "{{ central_api_image }}"

    - name: Deploy Central Postgres
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition: "{{ lookup('template', '../kubernetes/central/postgres.yaml') }}"
      vars:
        namespace: "{{ env_name }}-application"
        image: "{{ postgres_image }}"

    # - name: Deploy Central Frontend
    #   kubernetes.core.k8s:
    #     kubeconfig: "{{ kubeconfig }}"
    #     state: present
    #     definition: "{{ lookup('template', '../kubernetes/central/frontend.yaml') }}"
    #   vars:
    #     namespace: "{{ env_name }}-application"
    #     image: "{{ frontend_image }}"

    # --- 2. REGIONAL COUNTRY SERVICES ---
    - name: Deploy Regional Services
      include_tasks: regional_tasks.yml
      loop: "{{ countries }}"
      loop_control:
        loop_var: country_item