- name: "Manage Namespace for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Namespace
    name: "{{ env_name }}-{{ country_item.name }}"
    state: present

- name: "Apply GHCR Auth for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/common/ghcr-auth.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"

- name: "Deploy staging Vault secrets for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/staging-app-external-secret.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
  when:
    - env_name == "staging"

- name: "Deploy Regional Core API for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/core-deployment.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ country_item.core_image }}"

- name: "Deploy RabbitMQ for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/rabbit-mq_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ rabbitmq_image }}"

- name: "Deploy MailHog for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/mailhog_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ mailhog_image }}"

- name: "Deploy Alerting Service for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/alerting-service.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ country_item.alerting_image }}"

- name: "Deploy Regional Postgres for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/postgres_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ postgres_image }}"

- name: "Deploy pgAdmin for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/pgadmin_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ pgadmin_image }}"

- name: "Deploy Mosquitto for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/mosquitto_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ mosquitto_image }}"

- name: "Deploy Mosquitto UI for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/mosquitto-ui_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ mosquitto_ui_image }}"

- name: "Deploy MQTT Service for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/mqtt-service_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"
    image: "{{ country_item.mqtt_image }}"

- name: "Deploy Jaeger for {{ country_item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', '../kubernetes/regional/jaeger_brasil.yaml') }}"
  vars:
    namespace: "{{ env_name }}-{{ country_item.name }}"
    country: "{{ country_item.name }}"